name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install hatch

      - name: Install UV
        run: curl -LsSf https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh
  
      - name: Install ourself
        run: |
          uv pip install --system -e .

      # - name: Run hatch fmt check
      #   run: hatch fmt --check

      - name: Run tests
        run: hatch test --all -vv

      - name: Run coverage
        run: hatch run coverage xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
